apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ghost.fullname" . }}-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClass }}
  hostPath:
    path: /mnt/data/{{ include "ghost.fullname" . }}
  persistentVolumeReclaimPolicy: Retain
