apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.primary.persistence.existingClaim }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.global.storageClass }}
