apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  jannest_production_password: {{ .Values.auth.jannest_production_password | toString | b64enc | quote }}
