apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghost.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "ghost.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 2368
  type: {{ .Values.service.type }}
