apiVersion: v1
kind: Secret
metadata:
  name: jannest-blog-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  jannest_blog_password: {{ .Values.auth.jannest_blog_password | b64enc | quote }}