apiVersion: v1
kind: Service
metadata:
  name: jannest-blog-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: jannest-blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2368
  type: ClusterIP
