apiVersion: v1
kind: PersistentVolume
metadata:
  name: jannest-production-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /mnt/data/jannest-production
  persistentVolumeReclaimPolicy: Retain