apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jannest-web-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
